### ISSUE TITLE
Error when printing xml for failing test

### ISSUE THREAD

**Issue by przemeq84** [julias-shaw/speclj-junit#1]
When one of the test in a suite fails the library returns the following error: 

```
No implementation of method: :gen-event of protocol: #'clojure.data.xml/EventGeneration found for class: java.lang.AssertionError
```

or (if run with newer version of speclj):

```
No implementation of method: :gen-event of protocol: #'clojure.data.xml/EventGeneration found for class: speclj.SpecFailure
```

I guess it happens because speclj passes the `java.lang.AssertionError` object as a failure value of `speclj.results.FailResult` while the code expects pure string there.

**Comment by przemeq84** [comment]
Example of the simple code that returns error: https://gist.github.com/przemeq84/b2b6fbbbd44fa28014f3 just run `lein spec -f junit`

**Comment by julias-shaw** [comment]
Thanks for the fix przemeq84. I've merged your pull request and will publish a new release with it.
